use ard/env
use ard/io

use tinear/commands/login
use tinear/config
use tinear/tui/logged_in_screen
use tinear/tui/ui
use tinear/tui/welcome_screen

struct AppUiState {
  authed: Bool,
  api_key: Str,
  error: Bool,
}

fn app_content(cfg: config::Config) ui::Widget {
  ui::stateful(
    init: fn(_ctx: ui::BuildContext) AppUiState {
      AppUiState{authed: cfg.has_auth(), api_key: cfg.api_key, error: false}
    },
    build: fn(_ctx: ui::BuildContext, state: ui::State) ui::Widget {
      let model = state.value<AppUiState>()
      match model.authed {
        true => logged_in_screen::new(model.api_key),
        false => welcome_screen::new(
          api_key: model.api_key,
          has_error: model.error,
          on_changed: fn(value: Str) {
            state.set<AppUiState>(fn(mut next: AppUiState) {
              next.api_key = value
              next.error = false
            })
          },
          on_submit: fn(api_key: Str) {
            state.set<AppUiState>(fn(mut next: AppUiState) {
              if api_key.is_empty() {
                next.error = true
              } else {
                let ok = match login::login(api_key) {
                  ok(_) => true,
                  err(_) => false,
                }
                next.error = not ok
                if ok {
                  next.api_key = api_key
                  next.authed = true
                }
              }
            })
          },
        ),
      }
    },
  )
}

fn debug_wrap(child: ui::Widget) ui::Widget {
  let enabled = match env::get("DEBUG") {
    value => value == "true",
    _ => false,
  }
  match enabled {
    true => ui::key_debug(child),
    false => child,
  }
}

fn root(cfg: config::Config) ui::Widget {
  let quit_intent = "tinear.quit"
  ui::actions(
    child: ui::shortcuts(
      child: debug_wrap(ui::padding_horizontal(1, app_content(cfg))),
      bindings: [
        "Ctrl+c": quit_intent,
      ],
    ),
    bindings: [
      ui::action(quit_intent, fn(ctx: ui::EventContext, _intent: Str) ui::EventResult {
        ui::quit(ctx)
        ui::EventResult::handled
      }),
    ],
  )
}

fn run() {
  let cfg = try config::load() -> err { io::print("Unable to load config: {err}") }
  try ui::run(root(cfg)) -> err { io::print("Unable to run next UI: {err}") }
}
