use ard/async

use cooper/context
use tinear/models/issues

type Load = fn(Receiver<Bool>, fn([issues::BoardColumn]!Str))

struct Service {
  load: Load,
}

private fn cancelled(app: Receiver<Void>, view: Receiver<Bool>) Bool {
  select {
    app.recv() => true,
    view.recv() => true,
    _ => false,
  }
}

fn live(ctx: mut context::Context, api_key: Str) Service {
  let app_cancellation = ctx.cancellation
  let dispatch = ctx.dispatch
  Service{
    load: fn(view_cancellation: Receiver<Bool>, completion: fn([issues::BoardColumn]!Str)) {
      async::start(fn() {
        if not cancelled(app_cancellation, view_cancellation) {
          let result = issues::load(api_key)
          if not cancelled(app_cancellation, view_cancellation) {
            let _ = dispatch(fn() {
              completion(result)
            })
          }
        }
      })
    },
  }
}
