use ard/async

use cooper
use tinear/models/inbox

type Load = fn(Receiver<Bool>, fn([inbox::Item]!Str))
type LoadDetail = fn(Str, Receiver<Bool>, fn(inbox::Detail!Str))
type Archive = fn(Str, Receiver<Bool>, fn(Void!Str))

struct Service {
  load: Load,
  load_detail: LoadDetail,
  archive: Archive,
}

private fn cancelled(app: Receiver<Void>, view: Receiver<Bool>) Bool {
  select {
    app.recv() => true,
    view.recv() => true,
    _ => false,
  }
}

fn live(ctx: mut cooper::Runtime, api_key: Str) Service {
  let app_cancellation = ctx.cancellation
  let dispatch = ctx.dispatch
  Service{
    load: fn(view_cancellation: Receiver<Bool>, completion: fn([inbox::Item]!Str)) {
      async::start(fn() {
        if not cancelled(app_cancellation, view_cancellation) {
          let result = inbox::load(api_key)
          if not cancelled(app_cancellation, view_cancellation) {
            let _ = dispatch(fn() {
              completion(result)
            })
          }
        }
      })
    },
    load_detail: fn(notification_id: Str, view_cancellation: Receiver<Bool>, completion: fn(inbox::Detail!Str)) {
      async::start(fn() {
        if not cancelled(app_cancellation, view_cancellation) {
          let result = inbox::load_detail(api_key, notification_id)
          if not cancelled(app_cancellation, view_cancellation) {
            let _ = dispatch(fn() {
              completion(result)
            })
          }
        }
      })
    },
    archive: fn(notification_id: Str, view_cancellation: Receiver<Bool>, completion: fn(Void!Str)) {
      async::start(fn() {
        if not cancelled(app_cancellation, view_cancellation) {
          let result = inbox::archive(api_key, notification_id)
          if not cancelled(app_cancellation, view_cancellation) {
            let _ = dispatch(fn() {
              completion(result)
            })
          }
        }
      })
    },
  }
}
